# TOM v3.0 - Pre-Commit Hooks
# Verbot von Mocks in echten Tests (Real-Only Policy)

repos:
  - repo: local
    hooks:
      - id: forbid-mock-in-real-tests
        name: Forbid mock imports in real tests (component|integration|e2e)
        entry: bash -c 'if grep -r -E "from unittest import mock|unittest\.mock|import mock|from mock import" tests/(component|integration|e2e) --include="*.py"; then echo "❌ VERBOTEN: Mock imports in echten Tests (tests/(component|integration|e2e)/)!"; exit 1; fi'
        language: system
        pass_filenames: false
        
      - id: check-real-only-markers
        name: Check that real-only tests have proper markers
        entry: bash -c 'for f in tests/(component|integration|e2e)/*.py; do if ! grep -q "pytest.mark.real_only" "$f" 2>/dev/null; then echo "⚠️  Warnung: $f sollte pytest.mark.real_only haben"; fi; done'
        language: system
        pass_filenames: false
        
      - id: check-pytest-markers
        name: Verify pytest markers are properly used
        entry: bash -c 'python -m pytest --collect-only -q 2>&1 | grep -i "unknown" && echo "❌ Unbekannte Pytest Marker!" && exit 1 || true'
        language: system
        pass_filenames: false
        
      - id: python-lint
        name: Python Linting
        entry: bash -c 'python -m flake8 --max-line-length=120 --ignore=E203,E501,W503'
        language: system
        files: \.py$
        pass_filenames: true
