# TOM v3.0 - Prometheus Alert Rules

groups:
  - name: tom_realtime
    interval: 5m
    rules:
      - alert: HighE2ELatency
        expr: histogram_quantile(0.95, sum(rate(tom_realtime_e2e_ms_bucket[5m])) by (le)) > 800
        for: 5m
        labels:
          severity: critical
          component: realtime
        annotations:
          summary: "Realtime E2E latency high (p95 > 800 ms)"
          description: "Die Echtzeit-Ende-zu-Ende-Latenz überschreitet 800 ms (p95)."

      - alert: HighStageLatencySTT
        expr: histogram_quantile(0.95, sum(rate(tom_stage_latency_ms_bucket{stage="stt"}[5m])) by (le)) > 300
        for: 5m
        labels:
          severity: warning
          component: stt
        annotations:
          summary: "STT latency high (p95 > 300 ms)"
          description: "STT Stufe überschreitet 300 ms (p95)."

      - alert: HighStageLatencyLLM
        expr: histogram_quantile(0.95, sum(rate(tom_stage_latency_ms_bucket{stage="llm"}[5m])) by (le)) > 500
        for: 5m
        labels:
          severity: warning
          component: llm
        annotations:
          summary: "LLM latency high (p95 > 500 ms)"
          description: "LLM Stufe überschreitet 500 ms (p95)."

      - alert: HighStageLatencyTTS
        expr: histogram_quantile(0.95, sum(rate(tom_stage_latency_ms_bucket{stage="tts"}[5m])) by (le)) > 200
        for: 5m
        labels:
          severity: warning
          component: tts
        annotations:
          summary: "TTS latency high (p95 > 200 ms)"
          description: "TTS Stufe überschreitet 200 ms (p95)."

      - alert: GatewayBackpressure
        expr: increase(tom_ws_backpressure_events_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
          component: gateway
        annotations:
          summary: "Backpressure detected"
          description: "Das Gateway meldet Backpressure-Ereignisse."

      - alert: Gateway429Ratio
        expr: sum(rate(tom_ws_gateway_http_responses_total{code="429"}[10m])) / sum(rate(tom_ws_gateway_http_responses_total[10m])) > 0.05
        for: 10m
        labels:
          severity: warning
          component: gateway
        annotations:
          summary: "429 quota above 5%"
          description: "Mehr als 5% der Gateway-Antworten sind 429 (Rate Limit)."

      - alert: AudioDropRateHigh
        expr: (increase(tom_audio_frames_dropped_total[5m]) / clamp_min(increase(tom_audio_frames_sent_total[5m]), 1)) > 0.01
        for: 5m
        labels:
          severity: warning
          component: gateway
        annotations:
          summary: "Audio drop ratio above 1%"
          description: "Mehr als 1% der Audio-Frames wurden verworfen."

      - alert: SyntheticCallStale
        expr: time() - tom_synth_call_last_success_timestamp_seconds > 93600
        for: 5m
        labels:
          severity: warning
          component: synthetic
        annotations:
          summary: "Synthetic call missing (> 26h)"
          description: "Der letzte erfolgreiche Synthetic Call liegt länger als 26 Stunden zurück."

  - name: tom_gpu_usage
    interval: 5m
    rules:
      - alert: HighGPUUsage
        expr: dcgm_fb_used_bytes / dcgm_fb_total_bytes > 0.9
        for: 5m
        labels:
          severity: critical
          component: gpu
        annotations:
          summary: "High GPU Memory Usage (> 90%)"
          description: "GPU Memory Usage übersteigt 90%"

      - alert: GPUUtilizationHigh
        expr: dcgm_gpu_utilization > 95
        for: 10m
        labels:
          severity: warning
          component: gpu
        annotations:
          summary: "High GPU Utilization (> 95%)"
          description: "GPU Utilization konstant über 95%"

  - name: tom_rl_system
    interval: 10m
    rules:
      - alert: LowRLReward
        expr: avg_over_time(tom_rl_reward_average[10m]) < -0.2
        for: 10m
        labels:
          severity: warning
          component: rl
        annotations:
          summary: "Low RL Reward (< -0.2)"
          description: "RL System Reward unter -0.2 für 10 Minuten"

      - alert: HighRLBlacklistedVariants
        expr: tom_rl_blacklisted_variants_total > 2
        for: 5m
        labels:
          severity: critical
          component: rl
        annotations:
          summary: "Too many blacklisted variants (> 2)"
          description: "Mehr als 2 RL-Varianten blacklisted"

      - alert: RLLowExplorationRate
        expr: tom_rl_exploration_rate < 0.05
        for: 30m
        labels:
          severity: warning
          component: rl
        annotations:
          summary: "Low RL Exploration Rate (< 5%)"
          description: "RL Exploration Rate unter 5% für 30 Minuten"

  - name: tom_service_availability
    interval: 5m
    rules:
      - alert: ServiceDown
        expr: up{job=~"tom-.*"} == 0
        for: 1m
        labels:
          severity: critical
          component: service
        annotations:
          summary: "Service down: {{ $labels.job }}"
          description: "Service {{ $labels.job }} ist down"

  - name: tom_telephony
    interval: 5m
    rules:
      - alert: HighCallFailureRate
        expr: rate(tom_telephony_calls_failed_total[5m]) / rate(tom_telephony_calls_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: telephony
        annotations:
          summary: "High Call Failure Rate (> 10%)"
          description: "Telefonie Failure Rate übersteigt 10%"

      - alert: HighBargeInLatency
        expr: histogram_quantile(0.95, sum(rate(tom_telephony_barge_in_latency_seconds_bucket[5m])) by (le)) > 0.12
        for: 5m
        labels:
          severity: warning
          component: telephony
        annotations:
          summary: "High Barge-In Latency (p95 > 120ms)"
          description: "Barge-In Latenz übersteigt 120ms (p95)"

  - name: tom_toolhub
    interval: 5m
    rules:
      - alert: HighToolLatency
        expr: histogram_quantile(0.95, sum(rate(tom_tool_latency_ms_bucket{tool=~"autoteilepilot|pdf_catalog|chromadb"}[5m])) by (tool, le)) > 2000
        for: 5m
        labels:
          severity: warning
          component: toolhub
        annotations:
          summary: "High Tool Latency (p95 > 2s)"
          description: "Tool {{ $labels.tool }} Latenz übersteigt 2s (p95)"

      - alert: ToolCallFailureRate
        expr: rate(tom_tool_calls_failed_total[5m]) / rate(tom_tool_calls_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: toolhub
        annotations:
          summary: "High Tool Call Failure Rate (> 5%)"
          description: "Tool Call Failure Rate übersteigt 5%"

